//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.7905
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMsg", Namespace="http://schemas.datacontract.org/2004/07/Chat.Model")]
    public partial class ChatMsg : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FromRealNameField;
        
        private System.Nullable<int> FromUserIdField;
        
        private string MessageBodyField;
        
        private System.DateTime SendTimeField;
        
        private string ToRealNameField;
        
        private int ToUserIdField;
        
        private int cidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromRealName
        {
            get
            {
                return this.FromRealNameField;
            }
            set
            {
                this.FromRealNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FromUserId
        {
            get
            {
                return this.FromUserIdField;
            }
            set
            {
                this.FromUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody
        {
            get
            {
                return this.MessageBodyField;
            }
            set
            {
                this.MessageBodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendTime
        {
            get
            {
                return this.SendTimeField;
            }
            set
            {
                this.SendTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToRealName
        {
            get
            {
                return this.ToRealNameField;
            }
            set
            {
                this.ToRealNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToUserId
        {
            get
            {
                return this.ToUserIdField;
            }
            set
            {
                this.ToUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cid
        {
            get
            {
                return this.cidField;
            }
            set
            {
                this.cidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usp_GetHistroryMsg15_Result", Namespace="http://schemas.datacontract.org/2004/07/Chat.Model")]
    public partial class Usp_GetHistroryMsg15_Result : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FromRealNameField;
        
        private System.Nullable<int> FromUserIdField;
        
        private string MessageBodyField;
        
        private System.DateTime SendTimeField;
        
        private string ToRealNameField;
        
        private int ToUserIdField;
        
        private int cidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromRealName
        {
            get
            {
                return this.FromRealNameField;
            }
            set
            {
                this.FromRealNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FromUserId
        {
            get
            {
                return this.FromUserIdField;
            }
            set
            {
                this.FromUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody
        {
            get
            {
                return this.MessageBodyField;
            }
            set
            {
                this.MessageBodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendTime
        {
            get
            {
                return this.SendTimeField;
            }
            set
            {
                this.SendTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToRealName
        {
            get
            {
                return this.ToRealNameField;
            }
            set
            {
                this.ToRealNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToUserId
        {
            get
            {
                return this.ToUserIdField;
            }
            set
            {
                this.ToUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cid
        {
            get
            {
                return this.cidField;
            }
            set
            {
                this.cidField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IChatMgr")]
public interface IChatMgr
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatMgr/SetMessage")]
    void SetMessage(Chat.Model.ChatMsg msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMgr/GetMessage", ReplyAction="http://tempuri.org/IChatMgr/GetMessageResponse")]
    Chat.Model.ChatMsg[] GetMessage(int userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMgr/GetHistoryMessage", ReplyAction="http://tempuri.org/IChatMgr/GetHistoryMessageResponse")]
    Chat.Model.Usp_GetHistroryMsg15_Result[] GetHistoryMessage(int userid, System.DateTime begintime, System.DateTime endtime);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IChatMgrChannel : IChatMgr, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ChatMgrClient : System.ServiceModel.ClientBase<IChatMgr>, IChatMgr
{
    
    public ChatMgrClient()
    {
    }
    
    public ChatMgrClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ChatMgrClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChatMgrClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChatMgrClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SetMessage(Chat.Model.ChatMsg msg)
    {
        base.Channel.SetMessage(msg);
    }
    
    public Chat.Model.ChatMsg[] GetMessage(int userid)
    {
        return base.Channel.GetMessage(userid);
    }
    
    public Chat.Model.Usp_GetHistroryMsg15_Result[] GetHistoryMessage(int userid, System.DateTime begintime, System.DateTime endtime)
    {
        return base.Channel.GetHistoryMessage(userid, begintime, endtime);
    }
}
